### ISSUE TITLE
Add Heroku Collorators

### ISSUE THREAD

**Issue by GeorgieGirl24** [GetThatFlightOut/Flight-API#3]
Add all teammates into Heroku Amadeaus API
- [x] elestes@gmail.com
- [x] cpfergus1@gmail.com
- [x] georgesoderholm@gmail.com
- [x] sagegonzales15@gamil.com
- [x] sheryl.stillman@gmail.com
- [x] aidanhansm@gmail.com
- [x] jesse.m.mellinger@gmail.com
- [x] nickmaxking@gmail.com
- [x] brian.b.liu@gmail.com
- [x] dunlapww@gmail.com

**Comment by cpfergus1** [comment]
Implemented 1/6/2021
